# External resource type
resource_types:
  - name: maven-resource
    type: docker-image
    source:
      repository: pivotalpa/maven-resource
      tag: latest
  #- name: maven-cache
  #  type: docker-image
  #  source:
  #    repository: abranxi/maven-cache-resource
  #    #repository: olhtbr/maven-cache-resource
  #    tag: latest
resources:
  # Git Resources
  - name: git-repo-all
    type: git
    source: &git_repo
      uri: git@github.com:abranxi/monorepo.git
      branch: master
      private_key: ((private-repo-key))
  - name: git-repo-global-lib
    type: git
    source:
      <<: *git_repo
      paths: ["global-lib-for-all-modules/**"]
  - name: git-repo-lib-for-a
    type: git
    source:
      <<: *git_repo
      paths: ["lib-for-service-a/**"]
  - name: git-repo-lib-for-b
    type: git
    source:
      <<: *git_repo
      paths: ["lib-for-service-b/**"]
  - name: git-repo-service-a
    type: git
    source:
      <<: *git_repo
      paths: ["service-a/**"]
  - name: git-repo-service-b
    type: git
    source:
      <<: *git_repo
      paths: ["service-b/**"]
  # Resource for caching Maven dependencies
  #- name: maven-cache
  #  type: maven-cache # Defined in resource_types
  #  source:
  #    <<: *git_repo     # We want to cache dependencies of the git-repo-all,
  #    paths:            # but interested only in the pom.xml, which declares dependencies
  #      - global-lib-for-all-modules/pom.xml
  #      - lib-for-service-a/pom.xml
  #      - lib-for-service-b/pom.xml
  #      - service-a/pom.xml
  #      - service-b/pom.xml
  #    settings:
  #      # Custom Maven settings.xml URL
  #      #url: 
  #      # Base pom.xml file
  #    #pom-file: pom.xml
  #    settings-file: ci/settings.xml
  # Nexus Resources
  - name: artifact-global-lib-for-all-modules
    type: maven-resource
    source: &artifact
      url: http://192.168.0.11:32768/repository/releases/
      snapshot_url: http://192.168.0.11:32768/repository/snapshots/
      artifact: com.test.monorepo:global-lib-for-all-modules:jar
      username: ((nexus-user))
      password: ((nexus-password))
  - name: artifact-lib-for-service-a
    type: maven-resource
    source:
      <<: *artifact
      artifact: com.test.monorepo:lib-for-service-a:jar
  - name: artifact-lib-for-service-b
    type: maven-resource
    source:
      <<: *artifact
      artifact: com.test.monorepo:lib-for-service-b:jar
  - name: artifact-service-a
    type: maven-resource
    source:
      <<: *artifact
      artifact: com.test.monorepo:service-a:jar
  - name: artifact-service-b
    type: maven-resource
    source:
      <<: *artifact
      artifact: com.test.monorepo:service-b:jar
   # Semver Resources   
  - name: global-lib-version
    type: semver
    source: &semver_conf
      driver: git
      uri: git@github.com:abranxi/monorepo.git
      branch: version
      file: global-lib-version
      private_key: ((private-repo-key))
  - name: lib-for-a-version
    type: semver
    source:
      <<: *semver_conf
      file: lib-for-a-version
  - name: lib-for-b-version
    type: semver
    source:
      <<: *semver_conf
      file: lib-for-b-version
  - name: service-a-version
    type: semver
    source:
      <<: *semver_conf
      file: service-a-version
  - name: service-b-version
    type: semver
    source:
      <<: *semver_conf
      file: service-b-version
      
jobs:
  - name: build-global
    serial: true
    plan:
    - get: git-repo-global-lib
      trigger: true
    - get: git-repo-all
    #- get: maven-cache  # Don't trigger on changes to the cache
    - put: global-lib-version
      params: {bump: minor}
    - task: build-global
      privileged: true
      #TODO externalize
      #file: git-repo-global-lib/ci/build-global.yml
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: latest
        inputs:
          - name: global-lib-version
          - name: git-repo-all
          #- name: maven-cache
        outputs:
          - name: global-output
          - name: git-repo-all-out
        run:
          path: git-repo-all/ci/build-global-lib-for-all-modules.sh
        #caches:
        #- path: /root/.m2/repository/
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
    - put: git-repo-all
      params: {repository: git-repo-all, rebase: true, only_tag: true, tag_prefix: global-lib-v, tag: global-lib-version/version}
    - put: artifact-global-lib-for-all-modules
      params:
        file: global-output/global-lib-for-all-modules-*.jar
        #pom_file: git-repo-all-out/global-lib-for-all-modules/pom.xml
        pom_file: global-output/pom.xml
  - name: build-lib-for-service-a
    serial: true
    plan:
    - get: git-repo-lib-for-a
      trigger: true
    - get: global-lib-version
      trigger: true
      passed: ['build-global']
    - get: git-repo-all
    - put: lib-for-a-version
      params: {bump: minor}
    - task: build-lib-for-service-a
      privileged: true
      #TODO externalize
      #file: git-repo-global-lib/ci/build-global.yml
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: latest
        inputs:
          - name: git-repo-all
          - name: lib-for-a-version
        outputs:
          - name: global-output
          - name: git-repo-all-out
        run:
          path: git-repo-all/ci/build-lib-for-service-a.sh
        #caches:
        #- path: /root/.m2/repository/
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
    - put: git-repo-all
      params: {repository: git-repo-all-out, rebase: true, only_tag: true, tag_prefix: lib-for-a-v, tag: lib-for-a-version/version}
    - put: artifact-lib-for-service-a
      params:
        file: global-output/lib-for-service-a-*.jar
        pom_file: git-repo-all/lib-for-service-a/pom.xml
  - name: build-lib-for-service-b
    serial: true
    plan:
    - get: git-repo-lib-for-b
      trigger: true
    - get: global-lib-version
      trigger: true
      passed: ['build-global']
    - get: git-repo-all
    - put: lib-for-b-version
      params: {bump: minor}
    - task: build-lib-for-service-b
      privileged: true
      #TODO externalize
      #file: git-repo-global-lib/ci/build-global.yml
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: latest
        inputs:
          - name: git-repo-all
          - name: lib-for-b-version
        outputs:
          - name: global-output
          - name: git-repo-all-out
        run:
          path: git-repo-all/ci/build-lib-for-service-b.sh
        #caches:
        #- path: /root/.m2/repository/
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
    - put: git-repo-all
      params: {repository: git-repo-all-out, rebase: true, only_tag: true, tag_prefix: lib-for-b-v, tag: lib-for-b-version/version}
    - put: artifact-lib-for-service-b
      params:
        file: global-output/lib-for-service-b-*.jar
        pom_file: git-repo-all/lib-for-service-b/pom.xml
  - name: build-service-a
    plan:
    - get: git-repo-service-a
      trigger: true
    - get: lib-for-a-version
      trigger: true
      passed: ['build-lib-for-service-a']
    - get: git-repo-all
    - put: service-a-version
      params: {bump: minor}
    - task: build-service-a
      privileged: true
      #file: git-repo-global-lib/ci/build-global.yml
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: latest
        inputs:
          - name: git-repo-all
          - name: service-a-version
        outputs:
          - name: global-output
          - name: git-repo-all-out
        run:
          path: git-repo-all/ci/build-service-a.sh
        #caches:
        #- path: /root/.m2/repository/
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
    - put: git-repo-all
      params: {repository: git-repo-all-out, rebase: true, only_tag: true, tag_prefix: service-a-v, tag: service-a-version/version}
    - put: artifact-service-a
      params:
        file: global-output/service-a-*.jar
        pom_file: git-repo-all/service-a/pom.xml
  - name: build-service-b
    plan:
    - get: git-repo-service-b
      trigger: true
    - get: lib-for-b-version
      trigger: true
      passed: ['build-lib-for-service-b']
    - get: git-repo-all
    - put: service-b-version
      params: {bump: minor}
    - task: build-service-b
      privileged: true
      #file: git-repo-global-lib/ci/build-global.yml
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: latest
        inputs:
          - name: git-repo-all
          - name: service-b-version
        outputs:
          - name: global-output
          - name: git-repo-all-out
        run:
          path: git-repo-all/ci/build-service-b.sh
        #caches:
        #- path: /root/.m2/repository/
        params:
          GIT_EMAIL: {{git-email}}
          GIT_NAME: {{git-name}}
    - put: git-repo-all
      params: {repository: git-repo-all-out, rebase: true, only_tag: true, tag_prefix: service-b-v, tag: service-b-version/version}
    - put: artifact-service-b
      params:
        file: global-output/service-b-*.jar
        pom_file: git-repo-all/service-b/pom.xml
